export const keyLabels = {
    "teamname": "Teamname",
    "school": "Schule",
    "kind-of-school": "Schulart",
    "plz": "PLZ",
    "city": "Stadt",
    "street": "Strasse",
    "street-nr": "Hausnummer",
    "betreuer0.name": "Betreuer 1: Nachname",
    "betreuer0.vorname": "Vorname",
    "betreuer0.email": "Email",
    "betreuer1.name": "Betreuer 2: Nachname",
    "betreuer1.vorname": "Vorname",
    "betreuer1.email": "Email",
    "betreuer2.name": "Betreuer 3: Nachname",
    "betreuer2.vorname": "Vorname",
    "betreuer2.email": "Email",
    "schueler0.name": "Teammitglied 1: Nachname",
    "schueler0.vorname": "Vorname",
    "schueler0.email": "Email",
    "schueler1.name": "Teammitglied 2: Nachname",
    "schueler1.vorname": "Vorname",
    "schueler1.email": "Email",
    "schueler2.name": "Teammitglied 3: Nachname",
    "schueler2.vorname": "Vorname",
    "schueler2.email": "Email",
    "schueler3.name": "Teammitglied 4: Nachname",
    "schueler3.vorname": "Vorname",
    "schueler3.email": "Email",
    "schueler4.name": "Teammitglied 5: Nachname",
    "schueler4.vorname": "Vorname",
    "schueler4.email": "Email",
    "schueler5.name": "Teammitglied 6: Nachname",
    "schueler5.vorname": "Vorname",
    "schueler5.email": "Email",
  };